name: Deploy Backend

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on:
        - self-hosted
        - Windows
        - X64

    steps:
      - name: Deploy backend
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
        
          Set-Location D:\BlueStreams\bluestreams-backend\code-with-quarkus
      
          pm2 stop backend
      
          git fetch origin
          git reset --hard origin/dev
      
          .\mvnw.cmd package -DskipTests
      
          pm2 restart backend
